#!/usr/bin/env python3
"""Derive the netlist of two cables mated at a connector pair.

Usage: chain_nets.py <cable1.nets.csv> <cable2.nets.csv> <CONN1>=<CONN2> [header text]
  e.g. chain_nets.py C1.nets.csv C2.nets.csv M12F=M12M > C3.nets.csv
Endpoints of the mated connectors are joined pin-by-pin and removed from the result.
"""
import csv, sys

def read(path):
    rows = csv.DictReader(l for l in open(path) if not l.startswith("#"))
    return [(r["signal"], set(r["endpoints"].split())) for r in rows]

def main():
    c1, c2, mate = read(sys.argv[1]), read(sys.argv[2]), sys.argv[3]
    a, b = mate.split("=")
    groups = [(sig, set(eps)) for sig, eps in c1 + c2]
    pins = {e.split(".", 1)[1] for _, eps in groups for e in eps if e.split(".")[0] in (a, b)}
    groups += [("", {f"{a}.{p}", f"{b}.{p}"}) for p in pins]
    merged = []
    for sig, g in groups:
        sigs = {sig} - {""}
        for m in [m for m in merged if m[1] & g]:
            merged.remove(m); g |= m[1]; sigs |= m[0]
        merged.append((sigs, g))
    key = lambda e: (e.split(".")[0], int(e.split(".")[1]) if e.split(".")[1].isdigit() else 999)
    nets = []
    for sigs, g in merged:
        eps = sorted((e for e in g if e.split(".")[0] not in (a, b)), key=key)
        if len(eps) > 1:
            nets.append(("/".join(sorted(sigs)), eps))
    nets.sort(key=lambda n: key(n[1][0]))
    print(f"# Chain of {sys.argv[1]} + {sys.argv[2]} mated at {a}={b} (generated by scripts/chain_nets.py)")
    if len(sys.argv) > 4:
        print(f"# {sys.argv[4]}")
    print("net,signal,endpoints")
    for i, (sig, eps) in enumerate(nets, 1):
        print(f"N{i:02d},{sig},{' '.join(eps)}")

if __name__ == "__main__":
    main()
